name: first github actions ci

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '24.15.0'
    - name: install dependencies
      run:  npm install
    - name:  run node test
      run:  node test.js